### ISSUE TITLE
Bulk generate projects per rank

### ISSUE THREAD

**Issue by alexanderabramov** [Expugn/priconne-quest-helper#14]
As a player that wants to raise a new character multiple ranks,
I want to quickly create 1 project per rank,
So that I can more easily prioritise only the next rank, and remove completed items.

It is convenient to have 1 project per character rank for two reasons:
- easy to verify that selected items are still correct and you have not forgotten to remove an item from the project at some point
- possible to prioritise only the next rank or 2

But it takes quite some clicking to create projects for e.g. ranks 8,9,10,11,12,13,14

Presets page could have a "generate projects" button that, for selected preset and range min-max rank, would generate projects, if they don't already exist, one per rank, called according to some naming convention.

**Current alternative**
1. manually create several projects
2. create only one project for all ranks

**Comment by Expugn** [comment]
I've added this suggestion in commit <https://github.com/Expugn/priconne-quest-helper/commit/2e655f771adbc4e8e3ce90e36fd6363c2484fe48>

However, I opted to not create a single project for every rank in case there were to be a user that wanted 2 or more ranks per project.  

Instead, the user selects their desired ranks and clicks the new `Load Items and Create Project` button to create a project with those items. I know this isn't exactly what you wished for, but hopefully it will be more helpful when creating those single rank projects!

Because of this change from your original suggestion, I'm unable to accept your pull request (<https://github.com/Expugn/priconne-quest-helper/pull/15>), but thank you anyways for taking the time to write it out!

**Comment by alexanderabramov** [comment]
@Expugn would you be open to change project name template so that character name comes first and level range after that?

I have another improvement in the queue to sort projects, and simple string sort is the easiest

**Comment by Expugn** [comment]
@alexanderabramov 

I could, but I kinda prefer having the rank before the character name.
I guess writing a way for people to edit the format is possible, but that's pretty complicated, lol.

Regarding sorting the project list, custom project names still are a possibility, so implementing a sort might cause inconveniences for people who prefer using `[1 - 14] Character` or any other project name that doesn't follow the format of `Character [1 - 14]`; that's why I never bothered sorting the list in the first place.

Also, I've looked through people's save data to see how people usually save their projects as, and a good amount of them are saved like `8콧코로` or `6월 노말2배`. That's just something to take account for if a sort is implemented.

I think the best solution for this would be to maybe have a drag/drop kind of deal where an user can adjust the positioning of projects to their liking, but that's probably pretty complicated.

Anyways, if a good reason for modifying the preset project name and implementing a sort presents itself, I'd be more than happy to do so, but as of right now I'm only able to see it causing more potential inconveniences than it's worth.
