### ISSUE TITLE
[Feature] Request to implement Chinese (Simplified) language support

### ISSUE THREAD

**Issue by chenyiping1995** [Expugn/priconne-quest-helper#26]
**Is your feature request related to a problem? Please describe.**
No, it's not in any related to a problem whatsoever. It's purely a feature request.

**Describe the solution you'd like**
The Bilibili (CN) server has been live for almost two months. I wonder if there's plan to implement Chinese translation (I'm happy to provide translation but I only saw the strings under `language`. Wondering if there's possibility to translate character and item names). Also is it possible to host a mirror to this project?

**Comment by Expugn** [comment]
I would need the strings to be translated for Chinese (Simplified) to be added. If you can, that would be great!
As of right now, it's not exactly possible to translate item names due to how I wrote the system but I plan on making changes to make this possible (no estimated time). One problem that this can have though is that newer items will need to be translated.
To translate character names and thematics, they can be found in the language files.
If you want to host a mirror, go ahead. I believe theres an existing mirror available somewhere already though for CN server.

**Comment by chenyiping1995** [comment]
Implemented #28.
