### ISSUE TITLE
Inventory Sorting

### ISSUE THREAD

**Issue by MonbanZ** [Expugn/priconne-quest-helper#38]
Hello, thank you for such great tools

Would it possible to have inventory sorting as per in game?
I really like to sync inventory list with in-game manually,1by1, in order, but new update with new equipment keep messing up the order.
Moreover when project completed, item got deleted from the list if nothing left (0 quantity) and I have to add the item back in which again messing up with order.

Thank you

**Comment by Expugn** [comment]
I'll see what I can do about sorting options. 

As for the item getting deleted from inventory of there's 0 quantity, that's intentional. The item still persists if quantity is set to 0 in case of a user input error. *I'm not sure if I want to modify this behavior.*

In case you weren't aware:

![SmartSelect_20210219-195517_Samsung Internet](https://user-images.githubusercontent.com/5342885/108583143-707caf80-72ec-11eb-8439-d00611b41794.jpg)

Items can be added to your inventory by clicking/tapping the item icon on the quest details. You can use this functionality to add items you don't have in your inventory or adjust how much you got from the quest.

EDIT: Another note, clicking/tapping on the number next to the crate image will allow you to type a specific number without you needing to click the buttons.

**Comment by MonbanZ** [comment]
I am well aware of the feature, and indeed it is really great UI/UX for quick update.

However, as the project increases, recommended quest list increase (with high & same quest score), and updating inline is taking more time and probably less accurate/efficient for node to node planning. Updating whole inventory first will give better overview and planning in my opinion, especially at the start of farm. This is just my preference to turn this tool as farm planner.

and I don't mind the 0 quantity behavior, the sorting feature will cover my intention.

Thank you

**Comment by Expugn** [comment]
Your suggestion should be live, thanks!

![image](https://user-images.githubusercontent.com/5342885/108606960-5685b000-7372-11eb-8386-44f6eda33780.png)
There is now a select list with sorting options here; choosing an option should perform the sort.

Do let me know if this wasn't the sorting method you had in mind.
