### ISSUE TITLE
Required Amount for Prioritized Project

### ISSUE THREAD

**Issue by AlterNirvana** [Expugn/priconne-quest-helper#39]
Hello,
Thank you for the wonderful app.
I have some suggestion.

**Is your feature request related to a problem? Please describe.**
There is a time when prioritize project has same item with non-prioritize project.
Some user want to focus on prioritized amount first. 
I think it is better to have view of total required for prioritize project specifically.

**Describe the solution you'd like**
Since we have "display amount required" and "substract amount from inventory" option in settings, another "display prioritize amount required" option may be better approach to display total required item for prioritize project. 

**Describe alternatives you've considered**
Display amount for prioritize project together with total required. For example on a item display:  x100(30) . 100 is total item required, 30 is prioritized item required
This might break the UI or make it messy/crowded. 

Thank you,

**Comment by Expugn** [comment]
Your suggestion should be live, thanks! (https://github.com/Expugn/priconne-quest-helper/commit/5bd69928a9178aa7743d15f57c087fc2a0056df1)

Here's how I implemented it:
Lets say I have the following Projects:
```
Project 1 (Prioritized): 10 Iron Sword
Project 2: 10 Iron Sword
```
Loading `[All Projects...]` will give me the following screen when the new setting `Display Priority Item Amount` is enabled:
![image](https://user-images.githubusercontent.com/5342885/115142582-75fa2b80-9ff7-11eb-8ace-daddba707e5b.png)
10 `Iron Blade`s that were required from the priority projects are shown instead of the 25 total required.

If I add 3 `Iron Sword` to my inventory with the `Subtract Amount From Inventory` setting enabled:
![image](https://user-images.githubusercontent.com/5342885/115142653-cec9c400-9ff7-11eb-96e9-b4652d521fc3.png)
The amount from inventory is subtracted from the Priority Project Amount Required. 
*If I had 15 `Iron Sword`s in my inventory instead, the Priority Project Amount Required will be displayed as 0.*

If I requested 5 `Iron Sword` (or any amount lower than the priority project amount required):
![image](https://user-images.githubusercontent.com/5342885/115142770-6af3cb00-9ff8-11eb-8b43-5b79f336a4e3.png)
The Priority Project Amount Required will still be displayed as such.
**If 5 or more `Iron Sword` is added to the inventory, the quests with `Iron Sword` will be removed as the Required Ingredients condition is satisfied despite the 10 `Iron Swords` needed to complete Priority Projects.**

Hopefully my implementation satisfies what you were suggesting.

**Comment by Kenjugs** [comment]
Would it be possible to recalculate quest scores once a prioritized item amount has been met via adding items to the inventory? Otherwise, you'll have a bunch of quests at the top of your list showing you need 0 items from them:

![image](https://user-images.githubusercontent.com/7631687/141924979-4ff5296b-81ef-4588-9ee5-b3602cbc0d65.png)

**Comment by Expugn** [comment]
@Kenjugs 
> Would it be possible to recalculate quest scores once a prioritized item amount has been met via adding items to the inventory? Otherwise, you'll have a bunch of quests at the top of your list showing you need 0 items from them:
> 
> ![image](https://user-images.githubusercontent.com/7631687/141924979-4ff5296b-81ef-4588-9ee5-b3602cbc0d65.png)

Sure, I've implemented the change here: https://github.com/Expugn/priconne-quest-helper/commit/5817b7457e363a92795de5d32d703aedb47c449a

Now, if you had a project setup like this:
```
Project 1 (Prioritized): Sun Amulet, Moon Bracelet, and Lion King Gauntlet
Project 2: Sun Amulet, Moon Bracelet, Congregation Pendant, and Justice God's Staff
```
![image](https://user-images.githubusercontent.com/5342885/141938898-5680acf6-4a25-4d33-8ee4-0dcc24d2d979.png)

Adding 20 `Moon Bracelet` and 20 `Sun Amulet` to your inventory (thus satisfying the prioritized project's requirements) will update the `Recommended Quests` to be:
![image](https://user-images.githubusercontent.com/5342885/141939108-59f62d45-f9bc-4d7d-8fb2-f3160a95c745.png)

Items that are still required by other projects will remain visible with their quantities set as 0 still, as seen below:
![image](https://user-images.githubusercontent.com/5342885/141939465-1ba925cc-aea5-4710-8dd6-d2950945e25a.png)

Hope this change makes your quality-of-life better.
(Also note that this will only be in effect if the `Subtract Amount From Inventory` and `Display Priority Item Amount` settings are both enabled.)
