### ISSUE TITLE
[Feature Request] Partially complete projects

### ISSUE THREAD

**Issue by tonyjphan** [Expugn/priconne-quest-helper#46]
Thanks for this excellent website Expugn! It's been super useful especially right now to track progress during 3x drops with the current EN 1.5 year anniversary.

**Is your feature request related to a problem? Please describe.**
There are often ranks where you can equip a few pieces of equipment at a time but haven't yet completed the project for that character's rank. The project is then out of date as your in-game inventory and characters' equipment no longer matches with your website inventory and project requirements.

**Describe the solution you'd like**
It'd be excellent if we could mark individual items within a project as complete, such as by clicking on the greyed-out item in the required ingredient list to open a drop down menu. The specific action I'm looking for is when marking an item as complete, it will both delete the item from your project and subtract the required amount of fragments/recipe items from your inventory.

**Describe alternatives you've considered**
When I equip items one at a time on some high priority characters as I acquire the necessary ingredients, I have to either:
1. Go to the item list and reduce the count of the items equipped by 1 + remove the correct number of items from my inventory
2. Duplicate the project twice and modify one duplicate to only contain the items I've equipped and the other to contain the items I don't yet have. I then mark the equipped one as complete and overwrite the original with the remaining item list

**Additional context**

**Comment by Expugn** [comment]
Interesting idea, I'll mull it over.

**Comment by Wazhai** [comment]
> Duplicate the project twice and modify one duplicate to only contain the items I've equipped and the other to contain the items I don't yet have. I then mark the equipped one as complete and overwrite the original with the remaining item list

I'll explain my own workaround which is similar to your second alternative, but (at least to me) seems less prone to mistakes. It's still a pretty clunky/annoying workflow but it's been working reliably for me.

1. clear item tables
2. go to Presets in bulk mode, select the character, then click on the respective items one by one as they get equipped in-game 
3. when done equipping, save this as a new project, then complete it to subtract the items from inventory
4. clear item tables
5. remake a project for the remaining items until my target rank for the character, using "load items from rank X to rank Y" as well as clicking items one by one in bulk mode as required

That said, it's not a great time to equip characters in the EN server right now, since we're about to get Legacy Equipment Data 2 early next month. It's best to prefarm for then with that equipment data.

**Comment by Expugn** [comment]
I've implemented your suggestion here: https://github.com/Expugn/priconne-quest-helper/commit/72f22fbdbf0164b46ec9e31df8debc7f0d1eb547
![image](https://user-images.githubusercontent.com/5342885/180706543-ae3082fd-1bac-45c4-bfa5-94b5fd1bd50f.png)

Now when you click on the `Complete Project`, the modal in the image will appear displaying a project's requested items and required ingredients.

Clicking on a requested item will reduce the count by `1` and consume ingredients from your inventory. Blacklisted ingredients are ignored when partially completing (they are grayed out, as you can see in image).

When partially completing, the blacklist status of an item **will not be removed**, compared to a full completion.

Clicking on the "Complete Project" button in this modal will complete the entire project as usual (inventory items are consumed and blacklist status on ingredients is removed).

As this is a feature that changed a good amount of things, you may expect uncaught issues/bugs when using it.
Please report any found issues that you find, thanks!

**Comment by tonyjphan** [comment]
Wow, what a quick turnaround! I'll test it out over the next few weeks and leave any additional feedback on the feature. Thanks!

**Comment by tonyjphan** [comment]
I did some testing today and found two things that could be considered bugs:

First, when trying to complete items that you don't have the full recipe for, nothing happens. In the below screenshot I'm unable to remove the 1x Octogram Pendant (requires 5x Octogram Pendant blueprint + 1x Victory Friendship Bracelet) because I don't have any Victory Friendship Bracelets in my inventory. It would also be nice if the items of ignored rarities could be hidden from the view:

![image](https://user-images.githubusercontent.com/12322401/182996978-7780aa24-e439-421c-8ea2-7e2a194018d3.png)

Since some higher tier items use ones of a lower tier in their recipes (which may belong to a rarity that's set to be ignored) could you allow for removing items from the list + consuming as many inventory items as possible down to 0, even if we don't have the required items in our inventory to do so?

Second, when fully completing a project, the item table is not cleared. Not sure if this intentional or if it was me misremembering what the previous functionality was like :)

**Comment by tonyjphan** [comment]
One more bug, you can click "Complete Project" when no project or `[All Projects]` is loaded. When you do, an empty popup appears with the button greyed out. The X on the top right doesn't do anything either, and only refreshing seems to fix things:

![image](https://user-images.githubusercontent.com/12322401/182998977-69956a97-f2e4-4977-b3d9-02dbf911ec0c.png)

Also, when opening `[All Projects]` after completing a project, then clicking "Complete Project", the popup shows the previous completed project instead of a blank one. Clicking items to try to complete them has no effect in this state and the red X is similarly nonfunctional:

![image](https://user-images.githubusercontent.com/12322401/182999691-efe17d88-1750-410a-beb4-a909e9cbde98.png)

**Comment by Expugn** [comment]
> First, when trying to complete items that you don't have the full recipe for, **nothing happens**.

This was intentional. I can change the functionality to "*still subtract items from inventory but not be so strict to force you to have enough to do something*" if you think it's better

> It would also be nice if the items of ignored rarities could be hidden from the view:

I'll make this change.

> Second, when fully completing a project, the item table is not cleared. Not sure if this intentional or if it was me misremembering what the previous functionality was like :)

To be honest, I forgot what the original complete button did too. I'm leaning toward that it just removed the project and items though. If you think clearing item tables after completion is better I'll make that change.

> One more bug, you can click "Complete Project" when no project or [All Projects] is loaded.

This shouldn't have been possible. You shouldn't be able to open the "Complete Project" modal with no project/`[All Projects]` loaded. I'll need to look into what I missed to fix that.

> Also, when opening [All Projects] after completing a project, then clicking "Complete Project", the popup shows the previous completed project instead of a blank one.

Probably because nothing was supposed to be loaded/updated when `[All Projects]` is selected, which is why it kept the previous project.

---

Anyways, thanks for taking the time to do some tests. I'll try to resolve all these issues over the next upcoming days depending on my free-time.

**Comment by tonyjphan** [comment]
Glad I could help, but I should be the one thanking you for providing such a useful resource to the community and for your responsiveness :)

> This was intentional. I can change the functionality to "still subtract items from inventory but not be so strict to force you to have enough to do something" if you think it's better

I would prefer this, as at the moment you cannot mark an item with a complex recipe such as a gold rarity Guardian Shield as complete unless you also have all of the silver/bronze items in your inventory

> To be honest, I forgot what the original complete button did too. I'm leaning toward that it just removed the project and items though. If you think clearing item tables after completion is better I'll make that change.

This one just felt off somehow but I don't find it too bothersome as the next action I take immediately after is to load up a different project/all projects :)

> Probably because nothing was supposed to be loaded/updated when [All Projects] is selected, which is why it kept the previous project.

Makes sense, and I'd imagine this would no longer be an issue once the issue above is fixed

---

I also ran into a new bug in the last hour - when completing a project with blacklisted items, they become unblacklisted. This doesn't apply to items that were removed via partial completion, only via the "Complete Project" button. However the changes to the blacklist don't persist upon refreshing (unless you click "Save Blacklist")

**Comment by Expugn** [comment]
> I also ran into a new bug in the last hour - ***when completing a project with blacklisted items, they become unblacklisted. This doesn't apply to items that were removed via partial completion, only via the "Complete Project" button.***

Intentional

> However the changes to the blacklist don't persist upon refreshing (unless you click "Save Blacklist")

I think that was how it always was, lol. Think the reason was in case you wanted to restore any changes you didn't want to make since you only have 1 global blacklist or something along the lines of that. Overall the blacklist feature has been relatively unpopular compared to inventory in terms of progress tracking from what I can tell so I don't know if I'll bother changing anything for now.

**Comment by Expugn** [comment]
Made bug fixes and added suggestions here: <https://github.com/Expugn/priconne-quest-helper/commit/f68a8422c3aaafe032f823b3b7b679a12c513126>

Gist of changes are:
- Text highlighting removed from "Complete Project" modal (was annoying getting text highlighted when spam partially clearing things)
- "Requested Items" in the "Complete Project" modal can now be partially completed regardless of inventory or blacklist status
- "Requested Items" that are rarities that are ignored in Settings will be changed to be low-opacity and be pushed to the back of the list instead of being hidden completely. This is because if a lower rarity component isn't ignored, it will be impossible to partially complete a project due to the parent "Requested Item" being missing completely.
- Fixed an issue where project completion status wasn't being updated after partially completing a project (technically completed projects won't get their status in the project list updated and the "Complete Project" button in the modal would never be enabled)
- Fixed an issue where the "Complete Project" button on the project tab would stay enabled if a project is completed through partial completion

If more issues are found with this feature, please don't hesitate in updating this GitHub issue. Thanks!
