### ISSUE TITLE
Cut Off in Project Details

### ISSUE THREAD

**Issue by zhuanghui-lin** [Expugn/priconne-quest-helper#48]
**Describe the bug**
When you are in the project details of a project, the missing fragments section is cut off.

**To Reproduce**
1. Go to Project Options for a project.
2. Click on 'Expand'
3. Zoom in and then back out.
4. Scroll down to Missing Fragments.
5. See error

**Expected behavior**
Being able to see the icon for the Missing Fragments instead of being halfway cut off.

**Screenshots**
![image](https://github.com/Expugn/priconne-quest-helper/assets/61763977/453224b2-9b5e-44f9-8e55-d7f82cabd6a5)

**Smartphone (please complete the following information):**
 - Device: iPad Pro (12.9-inch) (4th generation)
 - OS: iPadOS 17.0
 - Browser Safari
 - Version ???

**Additional context**

**Comment by Expugn** [comment]
Hi,
Apologies for the delayed response.

In the future I would prefer if this was in the appropriate issue tracker:
<https://github.com/Spugn/priconne-quest-helper/issues>

That being said, I've since increased the bottom margin to (hopefully) prevent cut-off. I don't have an iPad myself, so I'm unable to test for this specific device. Do let me know if you are still facing the same issues.
