### ISSUE TITLE
Prioritise important ranks

### ISSUE THREAD

**Issue by alexanderabramov** [Expugn/priconne-quest-helper#5]
As a player with a main roster of e.g. 5-7 chars that I plan to level all the way to max.

For immediate increase in power I need to know which equipment I need, for each char:
- for reaching important ranks 7 (and conceptually 4, but reached very fast anyway) that unlock skills
- for the current rank up
- for the next rank up (so when you rank up you already have something)

But long-term I also need to know all needed equipment (from the pieces that can drop in currently available missions). Knowing all needed equipment helps to see which ones are needed disproportionally (e.g. 3x more) to prioritize for farming and buying.

For example:
- after reaching 7, Rem still needs even more axes
- pink feathers

Looks like this use case is only useful if you are using the same team you want to rank (e.g. a new player or an alt), an not so useful for an established max-level account.

**Proposed solution**
Toggle in settings or project settings to "prioritize reaching rank 7" and "prioritize next rank".

If enabled they will adjust recommended mission list to:
- gray out items which are needed later, but lower priority, with intermediate "low priority" shade
- adjust mission score (or give a second "high priority score")

I do realize this is not very easy to implement since instead of keeping just a list of items in the project you'd need to keep a list of (character+ranks ) and a separate list to subtract which items are already acquired.

But the same structural change will also unlock other useful future UI improvements such as showing char tabs visually with "tap to disable item", and even further char screenshot recognition.

**Current alternative**
You can manually add equip up to and including 6 and then mentally keep a list of what's needed right now, and what's needed after 7

**Comment by Expugn** [comment]
The issue with implementing this idea is that the system wasn't designed with having character presets in mind originally; that idea came later.

However, this idea seems like an interesting one, so I'll try my hand on implementing it.  
I'll need to make some changes for this to work, and I won't be able to guarantee how long it'll take or if I'll be successful in doing so.

**Comment by Expugn** [comment]
While not being the exact solution that you suggested, I've implemented something that may suit your needs.

More information about the implementation here: https://github.com/Expugn/priconne-quest-helper/pull/7

-----

##### Example Use Case 1

* Load Preset for `Rem`: `Min Rank`: `1` | `Max Rank`: `7`
* Save as a new project and prioritize via the `Prioritize Project` button
* Load Preset for `Rem`: `Min Rank`: `8` | `Max Rank`: `13`
* Save as a new project
* Select `[All Projects...]` and click `Load Project`; both projects are now loaded which should equal the items that Rem needs to go from rank 1 -> 13.

Since the project containing Rem's items for rank 1 - 7 are prioritized, those items should have a higher quest score, meaning quests with those items should be placed higher than quests with items for Rem's rank 8 - 13.

A project containing troublesome items (i.e. `Lion Eagle's Feather`, `Wizard Boots`, `Invisible Dress`, `Lion King's Protective Charm`) can be created and prioritized as well.

##### Example Use Case 2

* Load Preset for `Rem`: `Min Rank`: `1` | `Max Rank`: `13`
* Save as a new project
* Load Preset for `Emilia`: `Min Rank`: `1` | `Max Rank`: `13`
* Save as a new project and prioritize via the `Prioritize Project` button
* Select `[All Projects...]` and click `Load Project`; both projects are now loaded.

Emilia and Rem's requirements are now loaded, but since Emilia's project is a priority her required wands, staves, and general mage/support gear should appear higher than Rem's axes (unless they share a common item).

-----

If this doesn't quite fit your needs, feel free to suggest a way to improve it.  

Due to the variability of projects, I doubt that a `Prioritize Rank 7` or `Prioritize Next Rank` feature would be easy to implement without huge system changes so I apologize for not being able to go with that route.
